### PR TITLE
Maskededtextbox

### PR DESCRIPTION
**Pull request by KristianMariyanov**
**This PR introduces a breaking change in the `kendo-inputs-common`**

- Change the configuration of the package to build, test and bundle TypeScript files;
- Remove `slider` and `switch` common files since they are deprecated;
- Add `maskedtextbox` common src files
- Add `maskedtextbox` tests

### CODE REVIEW

**Comment by tsvetomir** [comment]
@dtopalov @kspeyanski are you okay with these changes? We'll squash this PR as a breaking change in order to publish v3 in develop.

**Comment by kspeyanski** [comment]
As far as i'm concern, the `kendo-inputs-common` package is not used in any `kendo-react` packages, so we should not be affected by the changes.

**Comment by dtopalov** [comment]
During the major Slider and RangeSlider refactoring related to releasing the RangeSlider component, we also removed the dependency on `kendo-inputs-common` from `kendo-angular-inputs`.

**Review by tsvetomir — APPROVED** [review]

**Comment by tsvetomir** [comment]
We'll be changing the package prefix to `@progress` so this would effectively be a brand new package. Existing references will not be affected.

**Pull request merged**
